name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v3
         - name: set up JDK 11
           uses: actions/setup-java@v3
           with:
             java-version: '11'
             distribution: 'temurin'
             cache: gradle

          # Execute unit tests
         - name: Unit Test
           run: ./gradlew testDebugUnitTest
           
          
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug
        
        
    - name: Slack - Send Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,author,took,ref
        author_name: Action Test
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
        
        
    - name: Slack - Upload APK
      uses: MeilCli/slack-upload-file@v1.0.0
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}  
        initial_comment: ''
        channels: '개발'
        file_type: 'apk'
        file_name: 'app-debug.apk'
        file_path: './app/build/outputs/apk/debug/app-debug.apk' 
        

